### PR TITLE
Added cJTAG support

### PR DESCRIPTION
**Pull request by martinhannonashling**
Added support for cJTAG (2 wire) mode

### CODE REVIEW

**Comment by olerem** [comment]
hm... i hope cjtag support will go some day upstream. But this driver is hardbound to ftdi driver and not some thing upstreamable.
Why is it coupled with ftdi driver?

**Comment by abrodkin** [comment]
@anthony-kolesov I guess @olerem's point was why cJTAG implementation is not separated from the particular driver such that it could be re-used with other probes.

**Comment by olerem** [comment]
Sorry, i can't fallow your efficiency argumentation. The attached config is using "adapter_khz 2000" and comment says, it may work at 5MHz. The FTDI chip is capable to operate at 30MHz, but i was able to get stable configuration only with 15MHz, so even if cJTAG would work at 15MHz, USB wont be the slowest part of the chain. So, IMO, efficiency is nice, but it it should not prevent the code to be reusable for other adapters.
Why not follow the swd example? We have a common/reusable part and adapter specific code which allow to make it efficient.

**Comment by anthony-kolesov** [comment]
See #27 - changes are in master branch.

**Pull request closed without merging**
