### PR TITLE
Merge with openocd-0.10.0

### PR DESCRIPTION
**Pull request by mrnuke**
Might need to run ./bootstrap again if seeing any jaylink related issues during ./configure, but everything else seems to work fine.

I'd recommend making a new branch for this.

### CODE REVIEW

**Comment by anthony-kolesov** [comment]
Hi  Alexandru,

I cannot merge this into master, because OpenOCD requires too much of a new GNU Autotools. Even CentOS7 doesn't have necessary versions of autotools, but we have to support CentOS 6 in next release. With OpenOCD 0.9 it was ok to generate files on newer system and just run configure on CentOS 6, but with this 0.10 makefile tries to rerun autotools (because git doesn't preserve timestamps) and that returns an error (with 0.9 it would also rerun autotools but that wouldn't cause failure of a build process). It is possible to fix this by changing timestamps after checkout, but that seems to me to be too complex, considering that it might be needed to be redone after later checkouts. I can create a separate branch for 0.10 in our repo, but I cannot make it default since it doesn't work with both CentOS 6 and 7. To workaround this issue OpenOCD should be patched so that it wouldn't unconditionally run autoreconf - like it is done in GNU projects, where this happens only when maintainer mode is explicitly enabled.

Anton

**Comment by mrnuke** [comment]
Sounds reasonable. I can do the merge again, but without the autotools files, then that could go in a 0.10.0 branch.

**Comment by anthony-kolesov** [comment]
I already rebased it on top of v0.10: https://github.com/foss-for-synopsys-dwc-arc-processors/openocd/tree/arc-0.10-dev-2017.03

**Comment by mrnuke** [comment]
That's great! Thanks!

BTW, you can safely drop configs using 'ft2232'. The driver has been removed. It's all done with 'ftdi' now.

**Comment by anthony-kolesov** [comment]
Yes, I've dropped those in rebase, that conflicted with upstream change. Still has one left for AXS SDP, will drop in the cleanup for the upstreaming. Thanks, for patches!

**Pull request closed without merging**
